quarkus.langchain4j.openai.api-key=${ollama_API_KEY}

quarkus.langchain4j.openai.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.chat-model.log-requests=true
quarkus.langchain4j.openai.chat-model.log-responses=true

quarkus.langchain4j.ollama.chat-model.temperature=1.0
quarkus.langchain4j.ollama.chat-model.max-tokens=1000
quarkus.langchain4j.ollama.chat-model.frequency-penalty=0


quarkus.langchain4j.ollama.chat-model.model-id=granite3.3:2b
quarkus.langchain4j.ollama.devservices.image-name=ollama/ollama:rocm